### ISSUE TITLE
KeyNotFoundException and Null reference exception after modifying intersection with timed traffic lights

### ISSUE THREAD

**Issue by stkfd** [CBeTHaX/Skylines-Traffic-Manager#1]
I'm getting this exception (a LOT of them) after modifying an intersection with timed traffic lights. At least that is what I assume must have caused the exception, of course I can't be entirely sure. It is accompanied by a repeatedly popping up window with a Null reference exception, however that window only pops up when the simulation is not paused.

I've disabled all other traffic mods (Lane changer and switch traffic lights most notably) that I was using.

I'll keep experimenting and will update if i have more details on how to reproduce.

The error persists after I reload an earlier version of that same savegame (one without the modification to the said intersection). It does not occur on my other savegames

Screenshot of exception details:
http://prntscr.com/6vajra

**Comment by SvetlozarValchev** [comment]
I made some changes, check if ou are still getting that exception.

**Comment by stkfd** [comment]
Seems like that fixed it! I can now bulldoze a street on one side of the intersection and reattach it without any exceptions.
