### ISSUE TITLE
3-lane roads outer lane not used

### ISSUE THREAD

**Issue by GameBurrow** [CBeTHaX/Skylines-Traffic-Manager#4]
On 3-lane roads, it usually refuses to use the most outer lane. (same thing I see with highways and 6-lane roads).

![3laneproblem](http://i.imgur.com/dbdD543.jpg)
Version 1.01rc

**Comment by t3hk0d3** [comment]
+1 This is irritating and annoying.

**Comment by SvetlozarValchev** [comment]
Check in 1.04rc it should be better. Just make sure to wait a little so new pathfinding takes place (or clear traffic for faster effect)

**Comment by GameBurrow** [comment]
Looks better indeed
