### ISSUE TITLE
[SUGGESTION] Setting to make all new roads without traffic lights

### ISSUE THREAD

**Issue by GameBurrow** [CBeTHaX/Skylines-Traffic-Manager#5]
Allow to set how traffic lights appear by default.
For example I do not want any traffic lights on new roads.

**Comment by t3hk0d3** [comment]
This should be configurable, not a behavior by default.

**Comment by GameBurrow** [comment]
That's what I meant: Configurable parameter that allows you to choose which option is our default in the game.
